### ISSUE TITLE
Add the gradle wrapper under entity-services-examples

### ISSUE THREAD

**Issue by sastafford** [marklogic/entity-services#155]
I see the gradle wrapper in the root project folder but you will want to add it to the examples project root.

**Comment by jmakeig** [comment]
Why?

**Comment by sastafford** [comment]
OK, technically it is not necessary.  I'm used to putting the gradle wrapper in all of the subprojects.  So I don't have to run from a relative directory (i.e. ../gradlew mlDeploy).  I actually missed the part of running it from a relative directory.  I can live either way.  Your call.

**Comment by grechaw** [comment]
That method had not occurred to me before @sastafford .  In fact I do some unpleasant things because I was having trouble with paths.  I think I'll give it a whirl -- if it makes IDEs and command line play better together than I'll be happy to commit the wrapper to another location.

**Comment by grechaw** [comment]
I added the wrapper to the examples project in develop branch.  I'd like to leave this in 'fix' though until I update the README.  I'm not completely confident about the way we've set up ml-gradle resources for this project, given how two sub-projects share a top-level config, while the other two sub-projects each have their own.

**Comment by jmakeig** [comment]
How do we figure out if we’re “doing it right”, both from the Gradle and the ml-gradle perspective?

@rjrudin @sastafford

**Comment by grechaw** [comment]
In terms of how we work with unit + functional tests from QA I'm pretty sure we're in uncharted waters.
To me, the tradeoff is that, right now the tests all run OK, and take a while to setup/teardown.  Adding one more mldeploy will slow it down even more, and take a little effort to get right and move ahead.

It also might turn out that we need more than one examples db... or we may want to spin examples off into another repository.

**Comment by jmakeig** [comment]
> or we may want to spin examples off into another repository

I’d prefer not to do that. There is value in having the examples more easily discoverable.

**Comment by sastafford** [comment]
@grechaw - "one more mldeploy will slow it down even more"  

What did you have in mind that you would need another application deployment?  You could reuse the same database/appserver and just wipe the data between runs.

**Comment by grechaw** [comment]
@sastafford I've trained myself now toward `./gradlew mlReloadModules` or the analogous finer-grained commands, which does indeed speed up deployment a lot.  I've refactored the examples directory quite a bit (I'm going to put WIP work in a PR shortly) in order to leverage one directory per example.  I like having the wrapper there available for examples, and so I'm leaning toward just resolving this task with the new wrapper in place.

**Comment by rjrudin** [comment]
FWIW, I run "g -i mlreloadmod" (I'm too lazy to type "gradle", so I aliased "g" to it). I like "-i" for info-level logging, particularly for reloading modules, as I just like to verify the modules are getting loaded. And you don't have to type full task names in Gradle - as long as you type enough characters to uniquely identify the task, Gradle will figure it out. 

I run "mlreloadmod" all the time when I'm switching between branches, and once I'm ready to develop, I fire up "g -i mlw" (mlw = mlWatch), and that's it. Every now and then, I have to run mldeploydata to update my database because the database config changed. I only run mlDeploy as a last resort when things seem screwed up with my config.

**Comment by grechaw** [comment]
Good rules of thumb @rjrudin , will speed up dev cycle a lot.
