### ISSUE TITLE
ES guide : headline change 

### ISSUE THREAD

**Issue by rashiatmarklogic** [marklogic/entity-services#216]
Generate a Model from a Basic Model
should this be changed to "Generate a Model from Descriptor".

I find it very confusing to use Basic model for model descriptor.

**Comment by rashiatmarklogic** [comment]
model descriptor -> basic entity model -> model 

shouldnt it be :  model descriptor -> basic entity model -> persisted entity model

**Comment by rashiatmarklogic** [comment]
@bsrikan @grechaw 
subscribing you guys

**Comment by kcoleman-marklogic** [comment]
Since you didn't include a link to the content, it's hard to tell for sure what you're looking at, but I'm guessing you're talking about the Getting Started chapter. In future, please include a link. Also, it is better to use BugTrack for doc issues since the documentation is not maintained on GitHub. 

Be that as it may, one does not generate a model from a descriptor. The process goes model descriptor > basic model > model.  If you find this terminology confusing, you'll have to take it up with Justin. He's adamant that that last thing be called simply "the model", no adjectives allowed.

I intentionally didn't make a descriptor to basic model step in the Getting Started because in some cases this the descriptor IS a basic model, so this step is a no-op. If you guys think this is a problem, though, I can change it, of course.

**Comment by rashiatmarklogic** [comment]
Well, I do not think you need to add a separate step for descriptor to basic model because you have mentioned the validate function to do so. I am fine with "the model". Closing this issue
