### ISSUE TITLE
example races query(tab 4 and 9) show null values

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#246]
Run tab 04 and 09 from races examples.
Discussed with @grechaw and filing a bug for 9.0-1.

**Comment by grechaw** [comment]
What we have found is that the join keys for races satisfy both version one and version 2 envelopes, so once all of the versions are in the db together, the queries collide.

Interesting problem to consider while working on versioning example.

**Comment by grechaw** [comment]
I'll fix this issue by backing out version translation from the original races example, and creating a separate versioning example (as tracked in #141 )

**Comment by grechaw** [comment]
This issue is related to the new one I just created #252 

There are two things creating the cross-product.  having two templates that both index everything, and having a join key that isn't unique once the data is in the database.  Fixing #252 would solve this issue I believe.  If I can verify this with the existing races example then we might want not to take out the converted data, as it will not cause the same issues.

**Comment by bsrikan** [comment]
Shipping the bug as the issue seems to be fixed. Able to run qc tab 4 and 9 for races and dont see any null result. Results returned seems correct.
