### ISSUE TITLE
Use quotes consistently in codegen

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#261]
I've been working on workshop materials and noticed that sometimes I used single-quotes for strings in entity services codegen, and sometimes double-quotes.

Copying funcions into QC, I find it's much preferable to have all the same quoting, so I can wrap the whole module in the other delimiter to quote it.

I'd like to take the hit to our test keys to change this.  It's convenient to be able to treat a whole module as a string when you copy it into QC.

**Comment by kcoleman-marklogic** [comment]
It comforts me to know I am not the only person who does this!

FWIW, I've taken to using single quotes as much as possible in XQuery so that it "translates" easily when working through the same example in JS. 

Of course, pure JSON throws a monkey wrench in this strategy, but I find the data case comes up less often than the code one.

**Comment by grechaw** [comment]
This change is included now in the outstanding PR.

**Comment by bsrikan** [comment]
Regression running ok after key updates. Shipping the bug.
