### ISSUE TITLE
instance-json-from-document returns arrays incorrectly

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#364]
In the marklogic-data-hub project, @joecrean reports an issue with an entity services function.  See

http://github.com/marklogic-community/marklogic-data-hub/issues/708

**Comment by grechaw** [comment]
Started to take a look at this.    @joecrean has a proposed fix.  Analyzing why my existing tests did not surface this problem.

**Comment by grechaw** [comment]
My test cases did not have scalar values in arrays, only objects.  I'll make a new test case to cover this bug.

**Comment by grechaw** [comment]
Hi @joecrean I actually could not reproduce this issue, and I'm wondering what might be the same and different about your test data, or maybe if I fixed it in some other way earlier.  Can you forward me the XML envelope that is giving you the bad return for instance-json-from-document()?

**Comment by joecrean** [comment]
Hi @grechaw , i am soo sorry , I completely overlooked your original request for some details.  Here is a reduced/redacted test case.

```
import module namespace es = "http://marklogic.com/entity-services" at "/MarkLogic/entity-services/entity-services.xqy";

let $doc := document {
<envelope xmlns="http://marklogic.com/entity-services">
<headers/>
<triples/>
<instance>
  <info>
  <title>Foo</title>
  <version>0.0.1</version>
  </info>
  <Foo xmlns="">
    <keyword>1</keyword>
    <keyword>2</keyword>
    <keyword>3</keyword>
    <keyword>4</keyword>
    <keyword>5</keyword>
  </Foo>
</instance>
<attachments/>
</envelope>
}
return es:instance-json-from-document($doc)
```

**Comment by joecrean** [comment]
hi @grechaw 
just wanted to speak to your point about the use of a scalar array. Initially i created an entity definition with a couple of external entity references ; best example is for authors. However what i really wanted was a foreign key value. Entity Services expected me to generate an of author entities direct in my Foo entities. But I want to have the author entities separate with only foreign keys (and maybe some names) in my actual Foo entity. When you use an external entity reference it is like a structural convenience but not a foreign key relationship. So I might be happy to use Address in this way because I wont store them as separate entities but not Authors because I want to build up a store on all Authors and relate all kinds of data back to them. Hope that makes sense and for the issue hijacking.

**Comment by grechaw** [comment]
Your case clearly shows the issue.  I'm cross-eyed trying to figure what I've missed.  Anyhow, I've done the same thing as you to make simple foreign keys too.  If you define a ref, then the structure as you noted comes out a little differently.  As long as you know how to join your keys, I think using scalar values is a good alternative.

**Comment by grechaw** [comment]
I see now why I could not reproduce.  In order to handle arrays more gracefully in generally, the default serialization includes an attribute now for properties that are arrays.   Before this change arrays of a single element were being serialized as (non-array) scalars in JSON.

So the bugfix you've provided has no effect on OOTB envelopes, but the DHF may not have caught up with this change.  Therefore, we might as well put this fix into develop, so as to handle more serialization cases gracefully.

**Comment by grechaw** [comment]
This issue went into develop some time ago, but i neglected to move it along.

**Comment by bsrikan** [comment]
Tests added and running in regression. Shipping this.
